#!/usr/bin/env python3
"""
Module for advancing understanding of async programming through practical
comprehensions with generators.
"""
from typing import List
# Import async generator function from its module
async_generator = __import__('0-async_generator').async_generator


async def collect_async_floats() -> List[float]:
    """
    Execute async_generator to collect random floats asynchronously.
    This function utilizes an async comprehension to gather ten random
    float values generated by async_generator.

    Returns:
        List[float]: A list containing ten random floats generated asynchronously.
    """
    return [random_float async for random_float in async_generator()]
